"""add_email_verification_fields

Revision ID: 8fe5fcde88b9
Revises: b06b1a72008c
Create Date: 2026-07-06 21:34:41.269471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe5fcde88b9'
down_revision: Union[str, Sequence[str], None] = 'b06b1a72008c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default=sa.text("'PENDING'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
